[project]
name = "checks-mix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "six>=1.17.0",
]

[dependency-groups]
dev = [
    "mypy>=1.17.0",
    "pyrefly>=0.26.0",
    "ruff>=0.12.7",
]
